### PR TITLE
Fixed small code typo

### PR DESCRIPTION
**Pull request by surdu**

### CODE REVIEW

**Comment by NickIliev** [comment]
@surdu - why do you think this is a typo?

The callback methods can have a custom name and is better to have a descriptive custom name (e.g. like `onPageLoaded`, `onLabelLoaded`, `onStackUnloaded`) so we could have a better context where the callback have originated from. Of course, the event should be referenced as named by NativeScript(e.g. `loaded`, `unloaded`, `navigatedTo`, etc.)

**Comment by surdu** [comment]
@NickIliev Totally agree, but I believe it's a typo because at the bottom of the code we export the function as `exports.onLoaded = onLoaded;`.

**Comment by NickIliev** [comment]
Oh my.. nice catch! :)

**Review by NickIliev — APPROVED** [review]

**Comment by etabakov** [comment]
run ci

**Pull request merged**
