### PR TITLE
fix: Update README.md

### PR DESCRIPTION
**Pull request by TheBinitGhimire**
Signed-off-by: Binit Ghimire <thebinitghimire@gmail.com>

Fixed some grammatical and linguistic issues!

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?
As of now, there are some grammatical issues present in the _README.md_ file.

## What is the new state of the documentation article?
I have made changes to the existing grammatical and linguistic issues in the documentation article.

### CODE REVIEW

**Comment by TheBinitGhimire** [comment]
Would you mind letting me know how I can sign the CLA?

**Comment by TheBinitGhimire** [comment]
Thank you for letting me know about the CLA through email!

I just signed the CLA through Google Forms.

Looking forward to see the updates to this PR!

**Comment by TheBinitGhimire** [comment]
Thank you for letting me know about the CLA through email!

I just signed the CLA through Google Forms.

Looking forward to see the updates to this PR!

**Comment by TheBinitGhimire** [comment]
Thank you for letting me know about the CLA through email as well as this conversation!

I just signed the CLA through Google Forms.

Looking forward to see the updates to this PR!

**Comment by TheBinitGhimire** [comment]
@cla-bot check

**Comment by TheBinitGhimire** [comment]
Looking forward to see the updates regarding this PR!

**Review by tsonevn — APPROVED** [review]

**Pull request merged**
