### PR TITLE
Updated readme file for Android Build

### PR DESCRIPTION
**Pull request by baskarmib**
Updated the readme file for Android Build using Sidekick. Changed wordings with Local Build option and Cloud Build option.

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the new state of the documentation article?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by vchimev** [comment]
Ping @ggarabedian.

**Comment by ggarabedian** [comment]
@baskar3078, the getting started articles were designed to introduce the Sidekick users to the cloud build feature and that's why there is no information about local builds. However, your addition is welcome and I know that the people using local builds will find it helpful. Thank you for your contribution!

**Comment by ggarabedian** [comment]
@baskar3078, the getting started articles were designed to introduce the Sidekick users to the cloud build feature and that's why there is no information about local builds. However, your addition is welcome and I know that the people using local builds will find it helpful. Thank you for your contribution!

**Comment by ggarabedian** [comment]
@baskar3078, the getting started articles were designed to introduce the Sidekick users to the cloud build feature and that's why there is no information about local builds. However, your addition is welcome and I know that the people using local builds will find it helpful. Thank you for your contribution!

**Comment by baskarmib** [comment]
@ggarabedian @vchimev Thanks for reviewing and merging the same.

**Comment by radeva** [comment]
Hi @baskar3078,

Congratulations on being one of the winners in the {N} First-time contributors contest! 

You can claim your prize by contacting us at nativescriptwinners[at]progress.com not later than Nov 30th 2018 . Make sure you send us the following info: 
👉Your full name 
👉Your email 
👉Your country or residence 

Best regards,
The NativeScript Team

**Pull request merged**
