### PR TITLE
Plamen5kov/update debug docs

### PR DESCRIPTION
**Pull request by Plamen5kov**
All the information is in the PR, someone might want to reformat the wording and structure.

### CODE REVIEW

**Review by NickIliev — APPROVED** [review]

**Review by etabakov — CHANGES_REQUESTED** [review]
Some of the screenshots should be redone, using standard why to highlight things in the User Interface.

**Comment by etabakov** [comment]
@NickIliev I removed most of the screenshots to make the article easier for maintenance and more unified with the rest of the content. Also fixed some typos and fixed the headings. The title of the article is also updated to be more descriptive. Take a look and let me know what do you think.

**Comment by NickIliev** [comment]
@etabakov the article is a bit large so we might consider using markdown TOC. Apart from that, all seems great!

**Comment by etabakov** [comment]
Good point, @NickIliev. A TOC was added.

**Review by etabakov — APPROVED** [review]

**Pull request merged**
