### PR TITLE
Fix search text field not being auto focused #938

### PR DESCRIPTION
**Pull request by etabakov**

### CODE REVIEW

**Review by Plamen5kov — COMMENTED** [review]
I actually like the way it was done before, is there a way to get the old html template with the .search-input. And also, how can I build it locally and test the fix?

**Comment by etabakov** [comment]
I'm not sure if we can control this template. However, I don't think the previous approach worked at all - you cannot select the element while it is hidden, which the old version is doing.

You can build locally and test following the steps in the README - https://github.com/NativeScript/docs#local-setup. Just checkout my branch of the docs repository and the rest is the same.

**Comment by Plamen5kov** [comment]
Thank you, I'll test it out locally.

**Comment by Plamen5kov** [comment]
I haven't been able to run the documentation on linux, so I can't test the fix on my machine. If you've tested it locally and it works and If you think the [attribute="value] way is sufficient fix, feel free to merge.

**Pull request merged**
