### PR TITLE
docs(core): Windows ain't comin' ...

### PR DESCRIPTION
**Pull request by vchimev**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?

Windows platform support is mentioned.

## What is the new state of the documentation article?

Windows platform support plans are no more.

### CODE REVIEW

**Comment by vchimev** [comment]
test

**Review by etabakov — APPROVED** [review]

**Review by NickIliev — APPROVED** [review]

**Comment by NickIliev** [comment]
test

**Comment by NickIliev** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by vchimev** [comment]
Hey @darind, could you please assist with the CI?

**Review by tsonevn — APPROVED** [review]

**Comment by tsonevn** [comment]
test

**Pull request merged**
