### PR TITLE
New System requirements and setup instructions

### PR DESCRIPTION
**Pull request by teobugslayer**

### CODE REVIEW

**Comment by teobugslayer** [comment]
Ping @ikoevska & @N3ll

**Comment by N3ll** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
Do you think we should continue claiming the support for node 0.10.x? It's archaic...

**Comment by teobugslayer** [comment]
@ErjanGavalji , according the Analytics stats, almost 19% of users are using node.js 0.10. If we are going to obsolete it, we should warn the users in advance. Perhaps the 1.5 release is a good opportunity to do so.

**Comment by ErjanGavalji** [comment]
@teobugslayer Well, 19% seem a lot to me (to break I mean)... Are we sure we ONLY count customers (not our build/test machines) having that installed on their machines? What is the timespan of these stats?

**Comment by ikoevska** [comment]
:+1:

**Pull request merged**
