### PR TITLE
docs(Linux): Updated instruction for Ubuntu 20.04 Fixed mising packages.

### PR DESCRIPTION
**Pull request by acoppola**
docs(Linux): Removed missing packages and added the ones necessary for a correct setup.

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?
The instructions are not updated for Ubuntu 20.04 FF. Had some errors following the docs

## What is the new state of the documentation article?
Fixed errors, I was able to configure NS

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by acoppola** [comment]
@cla-bot check

.

**Comment by acoppola** [comment]
@cla-bot check

**Comment by NathanaelA** [comment]
@acoppola - thanks, do you know if the instructions will still work on Ubuntu 16LTS and 18LTS?

**Comment by acoppola** [comment]
> @acoppola - thanks, do you know if the instructions will still work on Ubuntu 16LTS and 18LTS?

I haven't tried yet on those distribution, need time to set the VMs to check on those.

**Comment by NathanaelA** [comment]
Thank you for your changes; they do not work on 16.04 LTS, but I'll fix them up since I created a VM for 16, 18, and 20 LTS versions..

**Pull request merged**
