### PR TITLE
Update ActionBar's padding-top css property

### PR DESCRIPTION
**Pull request by DrQwertySilence**
Update ActionBar's padding-top css property from 10 to 24 units,
Source:
[Material guidelines: Metrics and keylines](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-keylines-spacing)

### CODE REVIEW

**Comment by etabakov** [comment]
run ci

**Comment by tjvantoll** [comment]
Looks good to me 👍🏻

**Review by tjvantoll — APPROVED** [review]

**Comment by etabakov** [comment]
run ci

**Comment by etabakov** [comment]
Thanks for the contribution, @DrQwertySilence!

**Pull request merged**
