### PR TITLE
TestBed Documentation added

### PR DESCRIPTION
**Pull request by hypery2k**
see #1370

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the new state of the documentation article?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Review by vakrilov — APPROVED** [review]
LGTM. This should be a angular-only content though.

**Comment by hypery2k** [comment]
should i make a new md with limit to angular, like here: https://github.com/NativeScript/docs/blob/master/docs/tooling/angular-cli.md ?

**Comment by tsonevn** [comment]
HI @hypery2k,
You can use `{% angular %} .... {% endangular%}` tags to mark, which part of the text should be shown only for NS Angular. You can check [this](https://github.com/NativeScript/docs/blob/f43d49d9198c27d49ff7150b7c9cee38cc3eafd6/docs/core-concepts/project-structure-app.md) article, where it is shown how to use those tags.

**Comment by hypery2k** [comment]
@cla-bot check

done ;)

**Review by andreacimino — COMMENTED** [review]
In order to make everything work I had to change the testing code to:

`import "@nativescript/angular/zone-js/testing.jasmine";
import {nsTestBedInit} from "@nativescript/angular/testing";
nsTestBedInit();
`
Notice the imports.

**Comment by hypery2k** [comment]
> In order to make everything work I had to change the testing code to:
> 
> `import "@nativescript/angular/zone-js/testing.jasmine"; import {nsTestBedInit} from "@nativescript/angular/testing"; nsTestBedInit(); `
> Notice the imports.

strange, because I took it from an running application. Did the npm/module structure changed in latest tns releases?

**Review by NickIliev — APPROVED** [review]

**Comment by vakrilov** [comment]
🎉 🎉 🎉

**Pull request merged**
