### PR TITLE
hiding the second improve btn from JS and NG SDK examples

### PR DESCRIPTION
**Pull request by tsonevn**
hiding the second improve btn from JS and NG SDK examples

### CODE REVIEW

**Review by NickIliev — APPROVED** [review]

**Comment by tsonevn** [comment]
run ci

**Comment by tsonevn** [comment]
run ci

**Comment by tsonevn** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by tsonevn** [comment]
run ci

**Comment by tsonevn** [comment]
test

**Comment by dtopuzov** [comment]
test

**Review by etabakov — APPROVED** [review]

**Pull request merged**
