### PR TITLE
chore: fix reference to Android App Bundle article in publishing

### PR DESCRIPTION
**Pull request by KristianDD**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?

Reference to Android App Bundle in publishing article does not work.

## What is the new state of the documentation article?

Reference to Android App Bundle in publishing article does work.

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by KristianDD** [comment]
run ci

**Comment by tsonevn** [comment]
test

**Comment by NickIliev** [comment]
test

**Comment by tsonevn** [comment]
test

**Pull request merged**
