### PR TITLE
docs: update webpack article

### PR DESCRIPTION
**Pull request by vchimev**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the new state of the documentation article?

Reflect `nativescript-dev-webpack@0.14.3` to the article.

### CODE REVIEW

**Comment by vchimev** [comment]
```
Using TypeScript 2.2.2 from /root/NativeScript/node_modules/typedoc/node_modules/typescript/lib
Error: /root/NativeScript/tns-core-modules/ui/frame/transition-definitions.android.d.ts(7)
 Cannot find name 'java'.
Error: /root/NativeScript/tns-core-modules/ui/frame/transition-definitions.android.d.ts(11)
 Namespace 'android' has no exported member 'animation'.
```

Ping @NickIliev and @tsonevn.

**Comment by dtopuzov** [comment]
run ci

**Comment by tsonevn** [comment]
run ci

**Comment by dtopuzov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Review by sis0k0 — APPROVED** [review]

**Pull request merged**
