### PR TITLE
Added guidance notes to changing of app icon and splash screen on iOS

### PR DESCRIPTION
**Pull request by VladimirAmiorkov**
When customizing the app icon and splash screen (storyboard) on iOS it happens that the changes are not applied directly. This is due to the way the iOS OS caches those resource, this is resolved by deleting the app and rebooting before doing `tns run ios`

### CODE REVIEW

**Comment by tjvantoll** [comment]
Hey @VladimirAmiorkov,

Unfortunately it looks like there are now a bunch of conflicts in this PR so it’s difficult to tell what has changed. Could you either rebase this or send a new PR?

**Comment by VladimirAmiorkov** [comment]
@tjvantoll I just pulled the production into my fork, seams ok and all green 👍  The commit with my change was https://github.com/NativeScript/docs/pull/501/commits/ccb886465329919265f9a1e9b56bd96db0f76274

**Comment by tjvantoll** [comment]
@VladimirAmiorkov Ok I see it now.

Would you mind if I implemented this with a slightly different approach? Personally I’d like to see this warning once, at the top, and using the {N} styles. Here’s my proposal:

> **WARNING**: Occasionally, the iOS operating system caches your application’s icons and launch screens. If you’re updating icons or launch screens and not seeing your changes, delete the application from your device or emulator, and redeploy.

**Comment by VladimirAmiorkov** [comment]
@tjvantoll That looks great, go ahead.

**Pull request closed without merging**
