### PR TITLE
Update ng-chapter-4.md

### PR DESCRIPTION
**Pull request by NevanElder**
tutorial(ng-chapter-4): change "continue to chapter 5" link to go to chapter 5 instead of 6 (non-existent)

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the new state of the documentation article?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by etabakov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
test

**Review by etabakov — APPROVED** [review]
Thanks for the correction!

**Pull request merged**
