### PR TITLE
MERGE AFTER 5.0 IS RELEASED docs: update for support library activity api

### PR DESCRIPTION
**Pull request by manoldonev**
NOTE: This is not going to be released with {N} 4.2 (currently only in master branch)

Related to https://github.com/NativeScript/NativeScript/pull/6129

### CODE REVIEW

**Review by vchimev — APPROVED** [review]

**Review by vchimev — COMMENTED** [review]
What do you think about explicitly mentioning that custom Android activities should inherit from:
- `android.app.Activity` for NativeScript <= 4.2.0,
- `andandroid.support.v7.app.AppCompatActivity` for later versions;
in this documentation article?

This is due to the luck of version specific NativeScript documentation.

In addition, could refer to the [PR](https://github.com/NativeScript/NativeScript/pull/6129) and migration steps.

**Comment by manoldonev** [comment]
I can make a note for this but do we have a general policy to provide docs versioning in this way?

**Review by tsonevn — APPROVED** [review]

**Comment by vchimev** [comment]
I don't know about a general policy, however, if we merge and publish these updates in the official docs we will mislead people: the feature is going to be released with 4.3, but the docs will say to use it right away.

Ping @etabakov in regards with the policy.

**Comment by etabakov** [comment]
The documentation should be merged/published when the features is available. The documentation should refer to the current version of {N}. If there are things that worth mentioning and a relevant for previous version, we can add a "Note" paragraph explaining what are the changes.

**Review by NickIliev — APPROVED** [review]

**Pull request merged**
