### PR TITLE
updating footer links

### PR DESCRIPTION
**Pull request by rdlauer**
adding blog and community links to sync up with main nativescript.org footer menu

### CODE REVIEW

**Comment by DimitarTodorov** [comment]
test

**Comment by dtopuzov** [comment]
test

**Comment by NickIliev** [comment]
test

**Comment by tsonevn** [comment]
test

**Comment by tsonevn** [comment]
test

**Comment by tsonevn** [comment]
test

**Comment by dtopuzov** [comment]
test

**Pull request merged**
