### PR TITLE
Link is broken in chapter 4. https://docs.nativescript.org/angular/start/tutorial/ng-chapter-4

### PR DESCRIPTION
**Pull request by Ksantacr**
Make sure to check the existing issues in this repository
Please, tell us what's the problem?
[x] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

Please, tell us more details

In chapter 4, the next chapter is 5 but it is link to 6 chapter (six is broken 
 404). Link must be ng-chapter-5 instead of ng-chapter-6

### CODE REVIEW

**Comment by etabakov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
test

**Review by etabakov — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
