### PR TITLE
docs: fix a note for what [(ngModel)] stands for

### PR DESCRIPTION
**Pull request by etabakov**
https://github.com/NativeScript/docs/issues/905

### CODE REVIEW

**Comment by etabakov** [comment]
Verified in this Playground: https://play.nativescript.org/?template=play-ng&id=RZySOR&v=5

**Review by vakrilov — CHANGES_REQUESTED** [review]
Can you change the quotes from `“` to `"` to avoid problems with copy-pasting

**Review by vakrilov — APPROVED** [review]

**Comment by etabakov** [comment]
Done, thanks!

**Comment by hackerunet** [comment]
I'm sorry to take my hands on this but, this seems to not been considering that commonly models are not described by just "email", a serious application would have models and references to those models exactly as angular does, I do understand that there could be some differences but, as far as I've been testing neither the documentation nor [text]="user.Email" (textChange)="user.Email=$event.object.text" works!! I got a context error in the chrome dev tools console and unfortunately I cannot trace this error far beyond. two way databinding is not easily possible in NS, if it is please consider adding some example of how to do it, at the very beginning with the simplest login page we need two way data binding and for new devs trying to get our hands dirty, is a serious fault to not have a correct documentation or real world examples how to acomplish the basic objective as update a model. Please can you be more specific how to implement 2 way DBiding using a model? thanks

**Comment by vakrilov** [comment]
Hey @hackerunet - thanks for the feedback.
The `[(ngmode]]="user.Email"` should work as expected (check out this [demo in playground](https://play.nativescript.org/?template=play-ng&id=RZySOR&v=6)). If it doesn't it is probably a bug - you can open an issue about it. Note: that it will not work is the `email` is null or undefined, so make sure you initialize this in components constructor or `ngOninit`. 
About the docs - [later on in the chapter](https://docs.nativescript.org/angular/tutorial/ng-chapter-3#33-structuring-your-app) we switch to using a `user` object which might be the thing you are looking for.

**Pull request merged**
